name: diarioped
description: A new Flutter project.
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  device_info_plus: ^9.1.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^13.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  intl: any

dev_dependencies:
  flutter_test:
        sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icon/icone.png"
  min_sdk_android: 21