name: diarioped
description: A new Flutter project.
publish_to: 'none'
version: 1.3.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  device_info_plus: ^11.5.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  flutter_svg: ^2.2.0
  go_router: ^16.1.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  win32: ^5.14.0
  intl: ^0.20.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
        sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icon/icone.png"
  min_sdk_android: 21